import LoanApplicationService from "@/classes/LoanApplicationServices";
import { ScalarLoanApplication } from "@/types/User";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const {
      userId,
      bankCurrentAccount,
      bankSavingAccount,
      bankNumberAccount,
      entity,
      ccNumber,
      fundsOrigin,
    }: ScalarLoanApplication = await req.json();

    const response = await LoanApplicationService.create({
      userId,
      bankCurrentAccount,
      bankSavingAccount,
      bankNumberAccount,
      entity,
      ccNumber,
      fundsOrigin,
      email: "",
      principal_debtor: "",
      co_debtor: "",
      affiliated_company: "",
      nit: "",
      requested_amount: "",
      deadline: 0,
      payment: "Semanal",
      quota_value: 0,
      current_loans: "Si",
      firtLastName: "",
      secondLastName: "",
      names: "",
      occupation: "",
      typeDocument: "CC",
      numberDocument: "",
      persons_in_charge: "",
      monthly_expenses: "",
      birthDate: undefined,
      place_birth: "",
      destination_resources: "",
      city: "",
      genre: "",
      marital_status: "",
      cellPhone: "",
      length_service: "",
      residence_address: "",
      residence_phone: "",
      housing_type: "Familiar",
      vehicle: "Si",
      whatsapp_number: "",
      pignorado: "",
      commercial_value: "",
      other_personal_assets: "",
      other_personal_commercial_value: "",
      family_members_in_company_agreement: "Si",
      is_currently_codebtor: "Si",
      other_entity: "Si",
      total_monthly_income: 0,
      total_monthly_revenues: 0,
      total_assets: "",
      total_liabilities: "",
      patrimony: "",
      court: undefined,
      number_employees: "",
      other_income_other_principal: "Si",
      personal_reference_name: "",
      personal_reference_work_company_name: "",
      personal_reference_city: "",
      personal_reference_address: "",
      personal_reference_number_phone: "",
      family_reference_name: "",
      family_reference_work_company_name: "",
      family_reference_city: "",
      family_reference_address: "",
      family_reference_number_phone: "",
      status: "Pendiente",
      fixed_term: "Si",
      labor_or_work: "Si",
      labor_seniority_contracts: "",
      contract_type_fixed_term: "Si",
      contract_type_work: "Si",
      date_relationship: undefined,
      labor_seniority: "",
      indefinite_term: "Si",
      average_variable_salary: 0,
      total_monthly_income_final: 0,
      monthly_discounts: 0,
      current_loans_affecting: "Si",
      terms_and_conditions: false,
      createdAt: undefined,
      updatedAt: undefined
    });

    return NextResponse.json({ success: true, data: response });
  } catch (error) {
    if (error instanceof Error) {
      return NextResponse.json({ success: false, error: error.message });
    }
  }
}
